### ISSUE TITLE
entity phases broken into individual words

### ISSUE THREAD

**Issue by timhutch** [BitCurator/bitcurator-nlp-entspan#1]
Not sure if this is a bug or just the current configuration ... but at least based on the bar graphs, entities which are phrases get broken up. E.g. John Smith and Ken Windsor get listed as John, Ken, Smith, Windsor on the graph. If there are entities Bob Smith and Bob Jones, the counts for each Bob are combined.

**Comment by kamwoods** [comment]
Noted. We'll be returning to work on this repo after current work on bitcurator-nlp-gentm and bitcurator-access-webtools hits a couple of scheduled checkpoints.

**Comment by kamwoods** [comment]
Closing as this repository is now end-of-life.
