### ISSUE TITLE
infile option expects subdirectory of nlp-entspan directory

### ISSUE THREAD

**Issue by timhutch** [BitCurator/bitcurator-nlp-entspan#3]
The --infile option for bcnlp_main.py only seems to work if the directory sits under the bitcurator-nlp-entspan

For example:
python bcnlp_main.py --infile /home/shared/entspan/myfiles
results in output including:
INIT: Extract contents for infile: /home/user/bitcurator-nlp-entspan//home/shared/entspan/myfiles
before getting to an error (returned non-zero exit status 2)

At this point it seems to be trying to textract the directory, but that turns out to be a red herring. If I add a symlink to the home directory, so that /home/user/bitcurator-nlp-entspan//home/shared/entspan/myfiles is valid, the whole process seems to run as expected.

There's a different error, but the same thing seems to be happening with bcnlp_createspan.py

**Comment by kamwoods** [comment]
Closing as this repository is now end-of-life.
